#!/bin/bash
#
echo "P 0, E 1, T 2, K 3, N 4, R 5, L 6, P 7"
echo "Kuna ära sõidate?"
read soit
echo "Mitu ööpäeva olete ära?"
read paevad
x=$(($paevad % 7))
tagasi=$(($soit + $x))
echo "Tagasi jõuate päeval: $tagasi"
